### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [Mkleemjr/prj-rev-bwfs-dasmoto#1]
You want to break your html up into sections by wrapping the related code in div tags:
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/34591944-db4a541c-f18e-11e7-8470-a5bb855a03df.png">
This will help you organized the html and make it more readable. It also will make it easier to style when we get into page layouts.

https://github.com/Mkleemjr/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/index.html#L18-L24

**Comment by Mkleemjr** [comment]
Makes sense. Thanks.
