### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [Mkleemjr/prj-rev-bwfs-dasmoto#3]
Right now you are setting the same font-family in many selectors. It would be more efficient to just set the default font for the whole page, which we can do with inheritance:
html { font-family: Helvetica; }
Now all elements will inherit this font as their default.

https://github.com/Mkleemjr/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/resources/style.css#L2

**Comment by Mkleemjr** [comment]
I was initially thinking to use the html selector, but wasn’t sure.
