### ISSUE TITLE
use classes efficiently

### ISSUE THREAD

**Issue by rimmesbe** [Mkleemjr/prj-rev-bwfs-dasmoto#5]
Do you need 3 classes with the same styling? Just create one class for all 3 of these components since they are all the same. The css' job is not to label or describe the content of the html, only to provide styling.
.price { color: blue; }

https://github.com/Mkleemjr/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsAndCrafts/resources/style.css#L32

**Comment by Mkleemjr** [comment]
Ok I see that. Thanks.
