### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Mkleemjr/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques. Take a look at the issues I created as they will point out some new techniques you should start implementing in your code. Here is a good article with some examples: 
http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by Mkleemjr** [comment]
Thank you for the feedback. I will look over all the issues. I want to become a great developer and programmer!
